version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dengue_survey_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dengue_user
      POSTGRES_PASSWORD: dengue_password
      POSTGRES_DB: dengue_survey
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dengue_user -d dengue_survey"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: dengue_survey_network

